services:
  - type: web
    name: alfabots-yt-api
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "export DENO_PATH=$HOME/.deno/bin/deno && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: API_KEYS
        sync: false
      - key: PROXY_LIST
        sync: false
      - key: COOKIE_ACCOUNT1
        sync: false
      - key: COOKIE_ACCOUNT2
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
